#!/bin/bash
set -e

cd $(dirname $0)

./build
./validate
./test -cover
./package
# Uncomment the following line to build the custom tyk image and comment the line above
#./package-custom-image

image=`cat ../bin/latest_image`

echo
echo Longhorn Manager image: ${image}
