#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

ARCH=${ARCH:-amd64}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

TAG=${TAG:-${IMAGE_TAG_PREFIX}${SUFFIX}}
REPO=${REPO:-tykio}
IMAGE=${IMAGE:-${REPO}/longhorn-manager:${TAG}}

if [ ! -e ./bin/longhorn-manager ]; then
    ./scripts/build
fi

trap 'rm -rf ./package/bin' exit

# update base image to get latest changes
BASE_IMAGE=`grep FROM package/Dockerfile  | awk '{print $2}'`
docker pull ${BASE_IMAGE}

docker buildx create --name multiarch --use
docker buildx inspect --bootstrap

#buildx build --platform linux/amd64,linux/arm64 -t ${IMAGE} -f package/Dockerfile --load .
docker buildx build --platform linux/amd64 -t ${REPO}/longhorn-manager:amd64 -f package/Dockerfile --load .
docker buildx build --platform linux/arm64 -t ${REPO}/longhorn-manager:arm64 -f package/Dockerfile --load .

docker build -t ${IMAGE} -f package/Dockerfile .

echo Built ${IMAGE}

echo ${IMAGE} > ./bin/latest_image
